# Generated by Django 4.2.7 on 2023-11-17 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 17, 18, 15, 34, 229926, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
